### ISSUE TITLE
Nf-boost deleting files used in upcoming processes

### ISSUE THREAD

**Issue by gacrestani** [bentsherman/nf-boost#4]
Hello, thanks for the plugin!

I am having some issues with it, though. It is apparently deleting intermediate files marked for use in upcoming processes. When running my pipeline (which I created myself), it fails with the following output error:
```
  Started on:	 shmoo
  Started at:	 Sun Sep 22 04:53:11 PM PDT 2024
N E X T F L O W  ~  version 24.04.3
WARN: It appears you have never run this project before -- Option `-resume` is ignored
Launching `main.nf` [maniac_ramanujan] DSL2 - revision: 18f2745068
B U R K E   L A B   P I P E L I N E
===================================

[09/950c2e] Submitted process > BwaMem (2)
[8d/c9fb27] Submitted process > BwaMem (1)
[12/2a6eab] Submitted process > BwaMem (3)
[86/cd95a7] Submitted process > BwaMem (4)
[c7/413b4c] Submitted process > BwaMem (6)
[fc/6081a8] Submitted process > BwaMem (5)
[93/079b6a] Submitted process > MergeSamFiles (2)
[87/efb7ac] Submitted process > MergeSamFiles (1)
[b4/08809a] Submitted process > MarkDuplicates (1)
[b2/01d53a] Submitted process > MarkDuplicates (2)
ERROR ~ Error executing process > 'MarkDuplicates (1)'

Caused by:
  Process `MarkDuplicates (1)` terminated with an error exit status (3)


Command executed:

  # gatk MarkDuplicates script
  # Defining the command
  cmd="gatk MarkDuplicates --INPUT CB_rep01_gen56.bam --METRICS_FILE CB_rep01_gen56_duplicate_metrics.txt --OUTPUT CB_rep01_gen56_duplicates_marked.bam --TMP_DIR /scratch"
  
  echo "$cmd"
  
  # Run command
  eval $cmd

Command exit status:
  3

Command output:
  gatk MarkDuplicates --INPUT CB_rep01_gen56.bam --METRICS_FILE CB_rep01_gen56_duplicate_metrics.txt --OUTPUT CB_rep01_gen56_duplicates_marked.bam --TMP_DIR /scratch

Command error:
  Using GATK jar /fs1/local/cqls/software/x86_64/gatk4-4.5.0.0/envs/gatk4/share/gatk4-4.5.0.0-0/gatk-package-4.5.0.0-local.jar
  Running:
      java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /fs1/local/cqls/software/x86_64/gatk4-4.5.0.0/envs/gatk4/share/gatk4-4.5.0.0-0/gatk-package-4.5.0.0-local.jar MarkDuplicates --INPUT CB_rep01_gen56.bam --METRICS_FILE CB_rep01_gen56_duplicate_metrics.txt --OUTPUT CB_rep01_gen56_duplicates_marked.bam --TMP_DIR /scratch
  17:03:55.009 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/fs1/local/cqls/software/x86_64/gatk4-4.5.0.0/envs/gatk4/share/gatk4-4.5.0.0-0/gatk-package-4.5.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
  [Sun Sep 22 17:03:55 PDT 2024] MarkDuplicates --INPUT CB_rep01_gen56.bam --OUTPUT CB_rep01_gen56_duplicates_marked.bam --METRICS_FILE CB_rep01_gen56_duplicate_metrics.txt --TMP_DIR /scratch --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --TAGGING_POLICY DontTag --CLEAR_DT true --DUPLEX_UMI false --FLOW_MODE false --FLOW_QUALITY_SUM_STRATEGY false --USE_END_IN_UNPAIRED_READS false --USE_UNPAIRED_CLIPPED_END false --UNPAIRED_END_UNCERTAINTY 0 --FLOW_SKIP_FIRST_N_FLOWS 0 --FLOW_Q_IS_KNOWN_END false --FLOW_EFFECTIVE_QUALITY_THRESHOLD 15 --ADD_PG_TAG_TO_READS true --REMOVE_DUPLICATES false --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --OPTICAL_DUPLICATE_PIXEL_DISTANCE 100 --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
  [Sun Sep 22 17:03:55 PDT 2024] Executing as crestang@shmoo.hpc.oregonstate.edu on Linux 5.14.0-362.24.1.el9_3.x86_64 amd64; OpenJDK 64-Bit Server VM 17.0.11-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.5.0.0
  [Sun Sep 22 17:03:55 PDT 2024] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.00 minutes.
  Runtime.totalMemory()=285212672
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  htsjdk.samtools.SAMException: Cannot read non-existent file: file:///scratch/nxf.wdz1YqbYGY/CB_rep01_gen56.bam
  	at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:498)
  	at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:485)
  	at htsjdk.samtools.util.IOUtil.assertInputIsValid(IOUtil.java:461)
  	at htsjdk.samtools.util.IOUtil.assertInputsAreValid(IOUtil.java:537)
  	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
  	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:280)
  	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
  	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
  	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
  	at org.broadinstitute.hellbender.Main.main(Main.java:306)

Work dir:
  /scratch/work/b4/08809a4967c06eccd9265346e27429

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

My workflow is:
```
workflow {
    Channel.fromPath("metadata/FLYLONG_metadata_nextflow.csv")
    | splitCsv(header:true)
    | map { row ->
        fastq1_path = params.samples_directory + "FLYLONG_" + row.population + "/" + row.fastq1
        fastq2_path = params.samples_directory + "FLYLONG_" + row.population + "/" + row.fastq2

        meta = row.subMap(
            'flow_cell',
            'lane',
            'population',
            'barcode',
            'sequencing_facility',
            'internal_library_name'
            )
        [row.population, meta, [
            file(fastq1_path, checkIfExists: true),
            file(fastq2_path, checkIfExists: true)]]
    }
    | filter { it.contains("EB_rep04_gen20") || it.contains("CB_rep01_gen56")}
    | set { samples }

    BwaMem(samples)
    MergeSamFiles(BwaMem.out.bam.groupTuple())
    MarkDuplicates(MergeSamFiles.out.bam)
    BaseRecalibrator(MarkDuplicates.out.bam)
    ApplyBQSR(BaseRecalibrator.out.bam)
    HaplotypeCaller(ApplyBQSR.out.bam)
    CombineGVCFs(HaplotypeCaller.out.vcf.collect(), HaplotypeCaller.out.vcftbi.collect())
    GenotypeGVCFs(CombineGVCFs.out.vcf)
    SelectVariants(GenotypeGVCFs.out.vcf)
    VariantFiltration(SelectVariants.out.vcf)
    
    SnpEff(VariantFiltration.out.vcf.flatten())
    VariantsToTable(SnpEff.out.vcf)
    
    VcfToTable(VariantFiltration.out.vcf.flatten())
}
```

And the processes up to the crash are:
```
process BwaMem {
    label 'low_reqs'
    
    input:
    tuple val(population), val(meta), val(reads)
    // For some reason I have to input reads as val instead of path, otherwise the process will not work

    output:
    tuple val(population), path("${reads[0].simpleName}_sorted.bam"), emit: bam

    script:
    """
    # bwa mem script
    # Defining the bwa-mem/samtools command

    # Defining RG
    RG="@RG\\tID:${meta.flow_cell}.lane-${meta.lane}.${meta.barcode}\\tSM:${population}\\tLB:${meta.internal_library_name}\\tPL:ILLUMINA\\tPU:${meta.flow_cell}.${meta.lane}.${meta.barcode}"

    # Defining the bwa mem | samtools command
    cmd="bwa mem -R '\$RG' ${params.reference_genome} -t ${task.cpus} ${reads[0]} ${reads[1]} | samtools sort --threads ${task.cpus} -o ${reads[0].simpleName}_sorted.bam"
    
    # Logging command
    echo "\$cmd"

    # Run command recording disk space before and after usage
    echo "Disk space before processing: "
    df -h /scratch

    eval \$cmd

    echo "Disk space after processing: "
    df -h /scratch
    """
}

process MergeSamFiles {
    label 'low_reqs'

    input:
    tuple val(population), path(bams)

    output:
    tuple val(population), path("${population}.bam"), emit: bam

    script:
    def bams_list = bams.collect{"--INPUT $it"}.join(' ')

    """
    # gatk MergeSamFiles script
    # Defining the command
    cmd="gatk MergeSamFiles ${bams_list} --OUTPUT ${population}.bam --TMP_DIR ${params.scratch_directory}"

    echo "\$cmd"

    # Run command
    eval \$cmd
    """
}

process MarkDuplicates {
    label 'medium_reqs'
    publishDir path: "${params.results_directory}/${population}", mode: 'copy', pattern: "*.txt"

    input:
    tuple val(population), path(bam)

    output:
    tuple val(population), path("${population}_duplicates_marked.bam"), emit: bam
    path("${population}_duplicate_metrics.txt")

    script:
    """
    # gatk MarkDuplicates script
    # Defining the command
    cmd="gatk MarkDuplicates --INPUT ${bam} --METRICS_FILE ${population}_duplicate_metrics.txt --OUTPUT ${population}_duplicates_marked.bam --TMP_DIR ${params.scratch_directory}"

    echo "\$cmd"
   
    # Run command
    eval \$cmd
    """
}
```

My `nextflow.config` file looks like this:
```
params {
    // Mandatory
    samples_directory   = '/nfs3/IB/Burke_Lab/Crestani/nextflow/fastqs/'
    reference_genome    = '/nfs3/IB/Burke_Lab/Crestani/nextflow/reference/dmel-all-chromosome-r6.51.fasta'
    bqsr_vcf            = '/nfs3/IB/Burke_Lab/Crestani/nextflow/reference/DGRP2.source_NCSU.dm6.final.vcf'
    results_directory   = '/nfs3/IB/Burke_Lab/Crestani/nextflow/results/'
    reports_directory   = '/nfs3/IB/Burke_Lab/Crestani/nextflow/results/reports'
    scratch_directory   = '/scratch'
    
    max_cpus            = 120
    max_memory          = '1T'
}

process {
    executor            = 'slurm'
    queue               = 'burke_lab'
    scratch             = '/scratch'

    withLabel: low_reqs {
      cpus              = 64
      memory            = '512G'
    }

    withLabel: medium_reqs {
      cpus              = 64
      memory            = '512G'
    }

    withLabel: high_reqs {
      cpus              = 128
      memory            = '512G'
    }
}

executor.queuesize	= 40


plugins {
  id 'nf-boost'
}

boost {
  cleanup = false
}


report {
  enabled = true
  file = "${params.reports_directory}/report.html"
  overwrite = true
}

trace {
  enabled = true
  file = "${params.reports_directory}/trace.txt"
  overwrite = true
}

timeline {
  enabled = true
  file = "${params.reports_directory}/timeline.html"
  overwrite = true
}

dag {
  enabled = true
  file = "${params.reports_directory}/dag.html"
  overwrite = true
}
```

If I set `cleanup = false`, the pipeline runs and completes without issues.
I am running Nextflow version 24.04.3 on my university's HPC (which uses SLURM).
I am likely doing something wrong! Can you please help me troubleshoot this?
Thank you very much!

**Comment by bentsherman** [comment]
@nservant this looks like the issue you were telling me about GATK using async I/O. I see `-Dsamjdk.use_async_io_write_samtools=true` in the command line, is that the flag you had to disable?

**Comment by nservant** [comment]
Indeed, I tested this parameter, but on my case, I think it is more a cluster I/O issue.
Increasing the `boost.cleanupInterval` to 180 sec fixed the issue.
But I guess tuning both parameters could be useful

**Comment by bentsherman** [comment]
@gacrestani try adding this setting to your nextflow config first:
```groovy
boost.cleanupInterval = `180s`
```

If that doesn't work then try disabling the flag I mentioned. But ideally the cleanup should be able to work with GATK's async I/O which will be more efficient. I think the default cleanup interval is just too short

**Comment by gacrestani** [comment]
Thank you. I will add the flag, rerun everything, and let you know how it goes.

**Comment by gacrestani** [comment]
A ran just crashed due to the same error.

```
[cqls-x86_64-tcsh crestang@shmoo nextflow]$ cat genomics_pipeline_trial70/genomics_pipeline_trial70.o100431 
  Started on:    shmoo
  Started at:    Mon Sep 23 02:49:28 PM PDT 2024
N E X T F L O W  ~  version 24.04.3
Launching `main.nf` [exotic_sinoussi] DSL2 - revision: 45e929d511
B U R K E   L A B   P I P E L I N E
===================================

[8a/d89358] Submitted process > BwaMem (1)
[20/1e8fd5] Submitted process > BwaMem (2)
[d6/8d2aa4] Submitted process > BwaMem (3)
[0c/fbeac6] Submitted process > BwaMem (5)
[f1/109c6b] Submitted process > BwaMem (4)
[a7/f46cc7] Submitted process > BwaMem (6)
[25/14158e] Submitted process > MergeSamFiles (1)
[49/20221b] Submitted process > MergeSamFiles (2)
[a6/b8f854] Submitted process > MarkDuplicates (1)
[b5/28c8b6] Submitted process > MarkDuplicates (2)
[2e/5a2a86] Submitted process > BaseRecalibrator (1)
[bb/acb235] Submitted process > BaseRecalibrator (2)
ERROR ~ Error executing process > 'BaseRecalibrator (2)'

Caused by:
  Missing output file(s) `EB_rep04_gen20_duplicates_marked.bam` expected by process `BaseRecalibrator (2)`
```

**Comment by njohner** [comment]
I'm having the same issue, with seemingly random files getting deleted although they are needed by downstream tasks. This is especially annoying since the resume does not work, which means that I have to rerun everything. I tried to increase the `cleanupInterval`, but that did not help. I finally had to give up on using this feature for now. I really hope this will become more stable in the future as it is a great addition to nextflow.

**Comment by bentsherman** [comment]
@njohner sorry it isn't working for you. if you can share a minimal example, that will give me the best chance at fixing it

**Comment by njohner** [comment]
I'll try to take a closer look and provide a minimal example, but as I said the failures are not systematic it might be a race condition or something alike. I'm running with slurm, which I guess might also play a role. I'll come back to you

**Comment by njohner** [comment]
So I finally managed to get a minimal example of failure. I have the issue with the `bbduk` nf-core module, and I could not reproduce the issue with simpler processes, so for now the example uses `bbduk`. The pipeline has just two bbduk processes chained. This is the beginning of preprocessing of metagenomics data. The first process trims the adapters, creating a log file which gets published to the output directory, as well as two fastq files (`GENGMAD069_trimmed_1.fastq.gz` and `GENGMAD069_trimmed_2.fastq.gz`) which are used as inputs for the second process.

I included everything needed to run the example in the attached archive, but as you'll see from the description below, you'd probably need a machine with SLURM (or maybe any other resource management system?) installed to reproduce the bug. I also attach a screen recording showing how the files get deleted.

Ok now a bit more about the issue and how to reproduce it:
- I only have the issue when using the `slurm` executor, and I could not reproduce it with the `local` executor
- The files get deleted while the next process is waiting in the queue. Notice that the directory for the next process has already been created, but the input files have not been symlinked yet.
- I set the `cleanupInterval` to something small, but that does not matter, as long as the next process which needs the files is in the queue (i.e. was submitted but has not started yet). 
- To have the second job hang in the queue I set the number of CPUs used to 2, while submitting to a queue only allowing for 1 CPU, that's why `BBDUK_FILTER_PHIX` uses 2 CPUs.
- I really don't understand why, but there are two other conditions that seem necessary to reproduce the bug:
  - Publish the log file of the first process (see `publishDir=...` in `nextflow.config`)
  - Generate the report (`report.enabled=true` in `nextflow.config`)
- If either of these two conditions is not satisfied, then it correctly only removes the log file but leaves the two `GENGMAD069_trimmed_?.fastq.gz` files in place, as they are needed by the  `BBDUK_FILTER_PHIX` process.
- The issue is reproducible at least with apptainer enabled or when running the pipeline as is (i.e. bbduk is installed on the node). In the attached archive I assume nextflow and bbduk are installed locally

Steps to reproduce:
- Machine with SLURM or maybe another queuing system installed
- ` conda env create -f environment.ym`
- `conda activate nf_boost_bug`
- Adapt the path in the `main.nf` file
- `nextflow run main.nf`
- make sure the cleanup happens while the second job is waiting in the queue

In the screen recording I show two tabs of my terminal, in the first one I start the pipeline and in the second one I show the content of the `work` directory, where the files get created by the first process and then cleaned-up although the second process has not started.
 
Sorry for the overly long message, but I hope that helps...
[nextflow_min_err.tar.gz](https://github.com/user-attachments/files/18108344/nextflow_min_err.tar.gz)

https://github.com/user-attachments/assets/dd45209f-8873-4e04-899f-d36062e06927

**Comment by bentsherman** [comment]
thanks @njohner for the detailed report. even if I can't reproduce it myself, when I have some time, hopefully I can trace the logic of the nf-boost cleanup with your run and figure out how it might delete files too early

**Comment by fgualdr** [comment]
I am having similar problems with picard.. wondering if I can set something like JAVA_OPTS = "-Dsamjdk.use_async_io=false" to the specific process affected.

**Comment by fmerinocasallo** [comment]
### Reproduction: nf-core/rnaseq 3.26 + `boost.cleanup` deletes shared `GUNZIP_RRNA_FASTAS` output while later `SORTMERNA` tasks still need it

Same failure class as this issue (cleanup removes files still required downstream). Observed on SLURM with Nextflow **26.04.2** and **nf-boost 0.7.0**.

#### Setup
- Pipeline: `nf-core/rnaseq` `-r 3.26.0`, Singularity, SLURM executor
- `executor.queueSize = 18` (lab overlay; staggered waves)
- `boost { cleanup = true; cleanupInterval = '180s' }` via plugin config
- Default `ribo_database_manifest` → HTTPS `smr_v4.3_fast_db.fasta.gz` → `PREPARE_GENOME:GUNZIP_RRNA_FASTAS` writes uncompressed FASTA under `work/`
- Per-sample `SORTMERNA` tasks only **symlink** to that gunzip output as `--ref`
- Pre-built `--sortmerna_index` supplied (index build skipped); FASTA still required for `--ref`

#### What happened (20-sample cohort, ~6 h wall)
1. `GUNZIP_RRNA_FASTAS` completed ~09:02 (`work/…/9c/b6502a…/smr_v4.3_fast_db.fasta`).
2. 16/20 `SORTMERNA` completed successfully through ~14:01 (symlink targets were live).
3. Workdir mtime on the gunzip task jumped to **14:52:30** — uncompressed FASTA gone; `.fasta.gz` staging symlink left.
4. At that moment `SRX3301680` was already submitted (14:39) and **not** finished; `SRX3301682` was submitted at **14:54** after the delete.
5. `SORTMERNA (SRX3301682)` failed in ~5 s: could not locate `smr_v4.3_fast_db.fasta` (dangling symlink) → exit 1 → pipeline `finish` / abort; ~17 children cancelled.

Nextflow also logged `Unrecognized config option 'boost.cleanup'` / `boost.cleanupInterval` at startup, but `CleanupObserver` still ran (`nf-boost@0.7.0`).

Cleanup broke the **live** DAG under queue throttling: a shared fan-out producer was removed while more consumers were still pending / not yet created.

#### Relation to #16
[#16](https://github.com/bentsherman/nf-boost/pull/16) (event order: `TaskPending` before parent `TaskCompleted`) looks like the right class of fix. Our gunzip parent completed hours earlier, so there may also be a refcount / late-wave issue when additional `SORTMERNA` tasks are created long after the producer finalized. Happy to test a build that includes #16 on this rnaseq pattern.

#### Operator hedge (independent of a plugin fix)
We now pass `--ribo_database_manifest` pointing at a **local uncompressed** FASTA under a stable DB path so `GUNZIP_RRNA_FASTAS` is skipped for that entry (nf-core 3.26 `prepare_genome` branches `.gz` vs plain). That removes this particular deletable fan-out product from `work/`.

Happy to share redacted `.nextflow.log` excerpts or a minimal channel topology if useful.

**Comment by njohner** [comment]
@fmerinocasallo it's easy to test #16 following https://github.com/bentsherman/nf-boost?tab=contributing-ov-file. I'd be interested to know if the fix works for you, and I'd really like to see that change getting merged as this issue has been bothering me for a while now...

**Comment by fmerinocasallo** [comment]
I've just opened [#18](https://github.com/bentsherman/nf-boost/pull/18) with a pending-claim stash fix (+ toRealPathOrAbsolute for ledger path identity). I tested on [nf-core/rnaseq](https://github.com/nf-core/rnaseq/) with cleanup enabled. It addresses the Pending-before-Completed delete race described here and in [#16](https://github.com/bentsherman/nf-boost/pull/16).
